#!/bin/bash -eu

OUTPUT_DIR=${OSREPORT_OUTPUT_DIR}/nova-hypervisors_info
mkdir -p ${OUTPUT_DIR}

HYPERVISORS_OUTPUT_DIR=${OUTPUT_DIR}/hypervisors
mkdir -p ${HYPERVISORS_OUTPUT_DIR}
openstack hypervisor list > ${HYPERVISORS_OUTPUT_DIR}/list
for i in $(openstack hypervisor list -c 'Hypervisor Hostname' -f value); do
    mkdir -p ${HYPERVISORS_OUTPUT_DIR}/${i}
    openstack hypervisor show ${i} > ${HYPERVISORS_OUTPUT_DIR}/${i}/info
    mkdir -p ${HYPERVISORS_OUTPUT_DIR}/${i}/servers
    openstack server list --all-projects --host ${i} > ${HYPERVISORS_OUTPUT_DIR}/${i}/servers/list
    for j in $(openstack server list --all-projects --host ${i} -c ID -f value); do
        ln -rs ${OSREPORT_OUTPUT_DIR}/nova_info/servers/${j} ${HYPERVISORS_OUTPUT_DIR}/${i}/servers/${j}
    done

    mkdir -p ${HYPERVISORS_OUTPUT_DIR}/${i}/agents/network
    openstack network agent list --host ${i} > ${HYPERVISORS_OUTPUT_DIR}/${i}/agents/network/list

    for j in $(openstack network agent list -c ID -f value); do
        ln -rs ${OSREPORT_OUTPUT_DIR}/neutron_info/agents/${j} ${HYPERVISORS_OUTPUT_DIR}/${i}/agents/network/${j}
    done
done

REGION_OUTPUT_DIR=${OUTPUT_DIR}/regions
mkdir -p ${REGION_OUTPUT_DIR}
openstack region list > ${REGION_OUTPUT_DIR}/list
for i in $(openstack region list -c 'Region' -f value); do
    mkdir -p ${REGION_OUTPUT_DIR}/${i}
    openstack region show ${i} > ${REGION_OUTPUT_DIR}/${i}/info
done

SERVICE_OUTPUT_DIR=${OUTPUT_DIR}/services
mkdir -p ${SERVICE_OUTPUT_DIR}
openstack service list > ${SERVICE_OUTPUT_DIR}/list
for i in $(openstack service list -c 'ID' -c 'Name' -f csv --quote none | grep -v ID); do
    id=$(echo ${i} | cut -d, -f1)
    name=$(echo ${i} | cut -d, -f2)
    mkdir -p ${SERVICE_OUTPUT_DIR}/${id}_${name}
    openstack service show ${id} > ${SERVICE_OUTPUT_DIR}/${id}_${name}/info
done