name: osreport
version: '1.3'
summary: Toolkit for debugging Openstack
description:
  Collects information from OpenStack Clouds
confinement: strict
grade: stable
base: core20
environment:
  TMPDIR: $SNAP_COMMON/tmp
  # need this due to pip python-certifi used by python-openstackclient
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt

apps:
  osreport:
    command: osreport/run.sh
    plugs: [home, network]
parts:
  checks:
    source: .
    plugin: dump
    stage-packages:
      - coreutils
      - bsdmainutils
      - jq
      - curl
      - tar
  openstackclients:
    plugin: python

    python-packages:
      - python-openstackclient
      - python-octaviaclient
    build-packages:
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - pkg-config
      - gcc

